In [34]:
# Create a Python List

# Initialize a Python list
python_list = [2, 4, 6, 8, 10]

In [35]:
# Display the list
python_list

[2, 4, 6, 8, 10]

In [36]:
# Import numpy library
import numpy as np

In [38]:
# Pass the Python list in np.array()
numpy_array1 = np.array(python_list)

# Display the numpy array
numpy_array1

array([ 2,  4,  6,  8, 10])

In [39]:
# Compare Python List and Numpy Array

In [51]:
# create two python list

X_list = [i for i in range(100000)]
Y_list = list(range(100000))

In [52]:
# Create two numpy array (say 'X' end 'Y') using above two list
X = np.array(X_list)
Y = np.array(Y_list)

In [53]:
# Define a function to calculate sum
# using python Lists X_list, Y_list)
def pure_python_version():
    Z = []
    for i in range(len(X_list)):
        Z.append(X_list[i] + Y_list[i])

In [54]:
# Define a function to calculate sum
# using numpy arrays (X, Y)
def numpy_version():
# In numpy we can directly perform
# sum element-wise as
    Z = X + Y 

In [55]:
# Import Timer class from timeit Library
from timeit import Timer

In [56]:
timer_obj1 = Timer("pure_python_version()", 
                   "from __main__ import pure_python_version")
timer_obj2 = Timer("numpy_version()", 
                   "from __main__ import numpy_version")

print("Pure python version:",timer_obj1.timeit(1000))
print("Numpy version:",timer_obj2.timeit(1000))

Pure python version: 5.681330832987442
Numpy version: 0.04294866599957459


In [57]:
5.681330832987442/0.04294866599957459

132.2818928309372

In [58]:
# Hence, pure python element-wise sum is much more than the Numpy arrays with 130 plus times better

In [61]:
numpy_array_of_first_five_even = np.array([i for i in range(1, 11) if i%2==0])

In [62]:
numpy_array_of_first_five_even

array([ 2,  4,  6,  8, 10])

In [63]:
numpy_array_of_first_five_even.size

5

In [64]:
numpy_array_of_first_five_even.dtype

dtype('int64')

In [65]:
float_arr = np.array([[0.4, 9.0, 0.1], [4.0, 2.0, 7.3]])

In [66]:
float_arr.shape

(2, 3)

In [67]:
float_arr.size

6

In [68]:
float_arr.dtype

dtype('float64')

In [70]:
float_arr.ndim # Checking the dimension of a numpy array

2

In [71]:
# Creating Basic NumPy Arrays

In [73]:
# 1st: array()
arr = np.array([[0.4, 9.0, 0.1], [4.0, 2.0, 7.3]])
arr

array([[0.4, 9. , 0.1],
       [4. , 2. , 7.3]])

In [86]:
# 2nd: arange() - This helps create collectionof a continuous integers
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# 3rd: zeros() - creates a collection of zero values
arr = np.zeros([5, 3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
# 4th: ones(): createsa collection of ones
arr = np.ones([4, 2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [84]:
# 5th: linspace() - generates values which are equally spaced from each other.
arr = np.linspace(start=5, stop=10, num=5)
arr

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [87]:
list_n = [2, 5, 8, 6, 4, 12, 16, 15]
arr = np.array(list_n)
arr.ndim

1

In [88]:
arr_z = np.zeros(10)
arr_z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
arr_linspa = np.linspace(start=17, stop=31)
arr_linspa

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [143]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [144]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [145]:

arr = np.append(arr, 56)
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 56])

In [146]:
arr = np.append(arr, [2, 6])
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 56,  2,  6])

In [147]:
arr = np.delete(arr, 56)
arr

IndexError: index 56 is out of bounds for axis 0 with size 13

In [148]:
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 56,  2,  6])

In [149]:
arr = np.delete(arr, 10)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6])

In [150]:
arr = np.append(arr, [65, 20, 1, 3, 4, 9, 6, 7])

In [151]:
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  6, 65, 20,  1,  3,  4,
        9,  6,  7])

In [152]:
# Sort
arr = np.sort(arr)

In [153]:
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  6,  6,  7,
        9, 20, 65])

In [ ]:
# Reshaping an Array
# use np.reshape() method
# note: there won't be any changes in the original data other than the shape


In [155]:
# create an array with 24 elements in it
arr = np.arange(24)
arr.shape

(24,)

In [158]:
# Reshaping in shape (8, 3)
arr_reshaped = np.reshape(arr, (8, 3))
arr_reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [174]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [175]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [176]:
L_to_np = np.array(L)
L_to_np

array([10,  2,  7,  8,  3, 22, 54, 12, 13, 46, 23, 25, 41])

In [177]:
L_to_np.sort()
L_to_np

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [178]:
np.delete(L_to_np, 4)

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [182]:
L_to_np = np.append(L, 53)

In [183]:
L_to_np.shape

(14,)

In [184]:
L_to_np.reshape((2, 7))

array([[10,  2,  7,  8,  3, 22, 54],
       [12, 13, 46, 23, 25, 41, 53]])

In [185]:
arr = np.array([10, 20, 30, 40])
arr

array([10, 20, 30, 40])

In [186]:
arr.ndim

1

In [188]:
# Positive single indexing in a numpy array
num_arr = np.array([[2, 4, 6], [8, 10, 12]])

In [189]:
num_arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [190]:
num_arr[0]

array([2, 4, 6])

In [196]:
num_arr[0][1] #arr[row_index, col_index]

4

In [194]:
# Positive Index Intervals in a NumPy Array
num_arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [198]:
num_arr[0, 0:2]

array([2, 4])

In [231]:
arr = np.array([[0, 1, 2, 3, 4],
               [5, 6, 7, 8, 9],
               [10, 11, 12, 13, 14]])

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [232]:
arr[1:3,2:5]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [233]:
arr[-2:,-3:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [234]:
# Striding in Python
# Striding - The steps to be taken while moving in a direction
# It is always good to understand through an example.

In [235]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [236]:
arr.ndim

1

In [237]:
arr = arr.reshape([5,5])
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [263]:
arr[[2]]

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

In [260]:
arr[1:4:2]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])